name: Deploy Dist
on: [push, workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Manual Clone
              run: |
                echo "Cloning repo..."
                git clone https://github.com/${{ github.repository }}.git